project:
  application: SpringCloud
  name: SpringCloud
  chineseName: SpringCloud工程Consumer
  version:  1.0
  unpackTime: 2020/08/01
  PIC: taojun
  versionControlNo: 1.0
  versionControlPath:
  framework: SpringBoot

server:
  port: 8087    #声明端口号

spring:
  application:
    name: nacos-consumer
#   nacos注册中心
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848

#   eureka注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka    #设置与eureka交互的地址，查询服务和注册服务都需要依赖这个地址，默认是：http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

feign:
  hystrix:
    enabled: true

logging:
  config: classpath:log/log4j2.xml