project:
  application: SpringCloud
  name: SpringCloud
  chineseName: SpringCloud工程服务提供方
  version:  1.0
  unpackTime: 2020/08/01
  PIC: taojun
  versionControlNo: 1.0
  versionControlPath:
  framework: SpringBoot

server:
  port: 8082    #声明端口号

spring:
  application:
    name: server-api

eureka:
  client:
    register-with-eureka: true    #默认是true，将自己注册到eureka上
    fetch-registry: false      #是否从eureka上获取信息，由于本案例是单机，无需从别的eureka上获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka    #设置与eureka交互的地址，查询服务和注册服务都需要依赖这个地址，默认是：http://localhost:8761/eureka


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health
  metrics:
    tags:
      application: ${spring.application.name}
ribbon:
  eureka:
    enabled: true
