project:
  application: SpringCloud
  name: SpringCloud
  chineseName: SpringCloud工程服务提供方
  version:  1.0
  unpackTime: 2020/08/01
  PIC: taojun
  versionControlNo: 1.0
  versionControlPath:
  framework: SpringBoot

server:
  port: 8082    #声明端口号

spring:
  application:
    name: server-api
  main:
    allow-bean-definition-overriding: true
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/ceshi2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driverClassName: com.mysql.jdbc.Driver
#    filters: log4j,wall,mergeStat
    druid:
      # 多数据源也可以通过@MapperScan(basePackages = {"***}, sqlSessionFactoryRef = "***")来配置
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/ceshi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: true
        url: jdbc:mysql://127.0.0.1:3306/ceshi2?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
      initial-size: 20
      max-active: 500
      min-idle: 200
      # 配置获取连接等待超时的时间
      max-wait: 60000
      validation-query: SELECT 1 FROM dual
      test-on-borrow: true
      test-on-return: false
      test-while-idle: false
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat
      min-evictable-idle-time-millis: 300000
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      web-stat-filter:
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        url-pattern: /*
        enabled: true
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: druid
        login-password: druid
        #IP白名单 (没有配置或者为空，则允许所有访问)
        allow:
        #IP黑名单 (存在共同时，deny优先于allow)
        deny:
        resetEnable: false
  redis:
    # redis数据库索引（默认为0），我们使用索引为3的数据库，避免和其他数据库冲突
    database: 0
    # redis服务器地址（默认为localhost）
    host: 127.0.0.1
    # redis端口（默认为6379）
    port: 6379
    # redis访问密码（默认为空）
#    password:
    # redis连接超时时间（单位为毫秒）
    timeout: 1000
    # redis连接池配置
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
        # true时连接池不生效, false时连接池生效, lettuce客户端不需要连接池，对性能没有提高，除非用到事务相关的特性再考虑设置连接池
        share-native-connection: true
#    jedis:
#      pool:
#        # 最大可用连接数（默认为8，负数表示无限）
#        max-active: 8
#        # 最大空闲连接数（默认为8，负数表示无限）
#        max-idle: 8
#        # 最小空闲连接数（默认为0，该值只有为正数才有作用）
#        min-idle: 0
#        # 从连接池中获取连接最大等待时间（默认为-1，单位为毫秒，负数表示无限）
#        max-wait: -1
  data:
    #mongobb配置
    mongodb:
      uri: mongodb://127.0.0.1:27017/test
    #es配置
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
#      cluster-name: myes
#      cluster-nodes: hadoop137:9300,hadoop138:9300,hadoop139:9300

elasticsearch:
  ip: 127.0.0.1
  tcpPort: 9300
  httpPort: 9200
  cluster:
    name: elasticsearch
  pool: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true

eureka:
  client:
    register-with-eureka: true    #默认是true，将自己注册到eureka上
    fetch-registry: false      #是否从eureka上获取信息，由于本案例是单机，无需从别的eureka上获取注册信息
    service-url:
      defaultZone: http://localhost:8761/eureka    #设置与eureka交互的地址，查询服务和注册服务都需要依赖这个地址，默认是：http://localhost:8761/eureka

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: info,health
  metrics:
    tags:
      application: ${spring.application.name}
ribbon:
  eureka:
    enabled: true

logging:
  config: classpath:log/log4j2.xml